name: Jest Regression Test

on: [push]

jobs:
  publish:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install modules
        run: yarn
      - name: Run Tests
        run: yarn jest
