name: Jest Regression Test

on: [push]

jobs:
  publish:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          node-version: 16.x
      - name: Install modules
        run: yarn upgrade
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4
