name: Jest Regression Test

on: [push]

jobs:
  publish:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16.x
      - name: Install modules
        run: yarn upgrade
      - name: Run Tests
        run: yarn jest
